### ISSUE TITLE
Feature Request - UI Improvement - Files

### ISSUE THREAD

**Issue by escfoe2** [arduino/lab-micropython-editor#131]
It would be very handy to have a panel on the side of the editor that loads the files on the board upon successful connection and show them within a simple tree-view structure on the right side of the editor.  We'll call it a File Tree Panel (name really only matters for the sake of this ticket).

Requirements:
- File Tree Panel - Shows all folders and file names
- File Tree Panel - Single or Double clicking a file will open it in the editor (as a new tab if not currently open)
- General UI - Menu Item to create a new file (and subsequently a tab) such as File > New Script/Tab

Nice to haves:
- General UX - Keyboard shortcut to create a new file (opens a new tab)
- General UI - Menu Button (Like Run, Stop, Reset, etc) to create a new file (opens a new tab)
- File Tree Panel - Collapsible
- File Tree Panel - Configurable to be mounted to the left or right of the editor
- File Tree Panel - Single or Double clicking a file that's already open will switch to that tab automatically
- General UX - When a new file is created while the app is connected to a board, it should be assumed the user wants this file on the board.  Transfer it as soon as the user saves it.  If some users disagree, make it an optional setting in the editor.

**Comment by ubidefeo** [comment]
We just released 0.11.0 which brings shortcuts and some bug-fixes as well as other nice things.

Re your feedback, we don't currently plan to have a sidebar for several reasons.

The new button file requires the option to let the user choose where it should be created.
The reason not to want the file to be default created on the board is because of how slow it is to work on the board compared to the host computer, and it's also easier to break file transfer.

Hope you'll like 0.11.0, though :)
