### ISSUE TITLE
No pop-up asking to save while closing

### ISSUE THREAD

**Issue by KirthanKamble** [arduino/lab-micropython-editor#96]
Refer title.

**Comment by ubidefeo** [comment]
This will be addressed in future updates, after 0.9.0

**Comment by ubidefeo** [comment]
This is now part of 0.9.1 when it comes to tabs with open files and changes (dirty `*` indicator), and will be including the whole application in 0.9.2.

If a file has never been saved and has changes we will not request confirmation.
It is up to the user to make the first save which will put the open file into a state including a check-before-close pass.

Closing issue since it is already addressed in latest release
